name: Deploy to Windows Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted # ← แก้ตรงนี้

    steps:
      - name: Pull latest code
        run: |
          cd C:\websites\mis-kpru
          git pull origin main

      - name: Install dependencies
        run: |
          cd C:\websites\mis-kpru
          npm install --production

      - name: Build
        run: |
          cd C:\websites\mis-kpru
          npm run build

      - name: Reload PM2
        run: |
          pm2 reload mis-kpru
