name: Deploy to Windows Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted # ← แก้ตรงนี้

    steps:
      - name: Fix git ownership
        run: git config --global --add safe.directory C:/websites/mis-kpru

      - name: Pull latest code
        run: |
          cd C:\websites\mis-kpru
          git pull origin main

      - name: Install dependencies
        run: |
          cd C:\websites\mis-kpru
          npm install

      - name: Build
        run: |
          cd C:\websites\mis-kpru
          npm run build

      - name: Reload PM2
        run: |
          Start-Process powershell -ArgumentList "-File C:\reload-pm2.ps1" -Verb RunAs -Wait
